apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-charges-model-deployment
  labels:
    app: insurance-charges-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-charges-model
  template:
    metadata:
      labels:
        app: insurance-charges-model
    spec:
      containers:
        - name: insurance-charges-model
          image: insurance_charges_model_service:latest
          ports:
          - containerPort: 80
            protocol: TCP
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "250m"
          env:
            - name: REST_CONFIG
              value: ./configuration/kubernetes_rest_config2.yaml
        - name: ambassador
          image: malexer/twemproxy
          env:
            - name: REDIS_SERVERS
              value: redis-st-0.redis-service.model-services.svc.cluster.local:6379:1,redis-st-1.redis-service.model-services.svc.cluster.local:6379:1
          ports:
            - containerPort: 6380
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-charges-model-service
spec:
  type: NodePort
  selector:
    app: insurance-charges-model
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
